version: "3.8"

services:
  bgp-scanner:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5500:5500"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: pm2 ecosystem.config.js
